# Model configuration for PlowPilot AI-Vision
# Target: YOLOv8n → ONNX → TensorRT (FP16)

model:
  name: "yolov8n"
  type: "object_detection"
  
  # Model files
  onnx_path: "models/yolov8n.onnx"
  trt_engine_path: "models/yolov8n_fp16.trt"
  trt_engine_int8_path: "models/yolov8n_int8.trt"
  
  # Input configuration
  input:
    width: 640
    height: 640
    channels: 3
    batch_size: 1
    data_type: "fp16"
  
  # Output configuration
  output:
    num_detections: 25200  # YOLOv8n output size
    num_classes: 80       # COCO classes
    confidence_threshold: 0.5
    nms_threshold: 0.45
    max_detections: 100
  
  # TensorRT settings
  tensorrt:
    precision: "fp16"  # fp16, int8, fp32
    workspace_size: 1024  # MB
    max_batch_size: 1
    optimization_level: 5
    builder_optimization_level: 5
    
    # INT8 calibration (if using int8 precision)
    int8_calibration:
      enabled: false
      calibration_data: "data/calibration/"
      cache_file: "models/yolov8n_int8_calibration.cache"
      num_calibration_samples: 100
  
  # Performance targets
  performance:
    target_inference_time: 20.0  # ms
    max_inference_time: 25.0     # ms
    target_fps: 30
    max_latency: 80.0            # ms p95

# Class labels (COCO dataset)
classes:
  - "person"
  - "bicycle"
  - "car"
  - "motorcycle"
  - "airplane"
  - "bus"
  - "train"
  - "truck"
  - "boat"
  - "traffic light"
  - "fire hydrant"
  - "stop sign"
  - "parking meter"
  - "bench"
  - "bird"
  - "cat"
  - "dog"
  - "horse"
  - "sheep"
  - "cow"
  - "elephant"
  - "bear"
  - "zebra"
  - "giraffe"
  - "backpack"
  - "umbrella"
  - "handbag"
  - "tie"
  - "suitcase"
  - "frisbee"
  - "skis"
  - "snowboard"
  - "sports ball"
  - "kite"
  - "baseball bat"
  - "baseball glove"
  - "skateboard"
  - "surfboard"
  - "tennis racket"
  - "bottle"
  - "wine glass"
  - "cup"
  - "fork"
  - "knife"
  - "spoon"
  - "bowl"
  - "banana"
  - "apple"
  - "sandwich"
  - "orange"
  - "broccoli"
  - "carrot"
  - "hot dog"
  - "pizza"
  - "donut"
  - "cake"
  - "chair"
  - "couch"
  - "potted plant"
  - "bed"
  - "dining table"
  - "toilet"
  - "tv"
  - "laptop"
  - "mouse"
  - "remote"
  - "keyboard"
  - "cell phone"
  - "microwave"
  - "oven"
  - "toaster"
  - "sink"
  - "refrigerator"
  - "book"
  - "clock"
  - "vase"
  - "scissors"
  - "teddy bear"
  - "hair drier"
  - "toothbrush"
